CREATE TABLE TR_F_MERCHANT (
  MERCHANT_ID VARCHAR2(36) NOT NULL PRIMARY KEY,
  MERCHANT_NAME VARCHAR2(50) NOT NULL,
  MERCHANT_CODE VARCHAR2(20) DEFAULT NULL UNIQUE,
  HOME_AREA VARCHAR2(15) DEFAULT 'deploy center' NOT NULL,
  CLASSIFIER VARCHAR2(45) DEFAULT 'classifier'
);
COMMENT ON COLUMN TR_F_MERCHANT."MERCHANT_ID" IS '商户ID';
COMMENT ON COLUMN TR_F_MERCHANT."MERCHANT_NAME" IS '商户名称';
COMMENT ON COLUMN TR_F_MERCHANT."MERCHANT_CODE" IS '商户code';
COMMENT ON COLUMN TR_F_MERCHANT."HOME_AREA2" IS '部署中心';

CREATE TABLE TR_F_DB (
  MERCHANT_ID VARCHAR2(36) NOT NULL PRIMARY KEY,
  DB_NAME VARCHAR2(50) NOT NULL,
  DB_USERNAME VARCHAR2(50) NOT NULL,
  DB_PASSWORD VARCHAR2(100) NOT NULL,
  INSTANCE_ID VARCHAR2(100) NOT NULL,
  PROXY_IP VARCHAR2(100) NOT NULL,
  PROXY_PORT VARCHAR2(100) NOT NULL,
  STATE CHAR(1) NOT NULL
);
COMMENT ON COLUMN TR_F_DB."MERCHANT_ID" IS '商户ID';
COMMENT ON COLUMN TR_F_DB."DB_NAME" IS '数据库名【密文】';
COMMENT ON COLUMN TR_F_DB."DB_USERNAME" IS '用户名【密文】';
COMMENT ON COLUMN TR_F_DB."DB_PASSWORD" IS '用户密码【密文】';
COMMENT ON COLUMN TR_F_DB."INSTANCE_ID" IS '实例ID';
COMMENT ON COLUMN TR_F_DB."PROXY_IP" IS '应用接入数据库的IP。PROXY代理给出的';
COMMENT ON COLUMN TR_F_DB."PROXY_PORT" IS '应用端口号';
COMMENT ON COLUMN TR_F_DB."STATE" IS '0-未创建；1-空闲（已创建，未分配）；2-在用（已分配给商户）；3-停用；4-销户；';