[links]
    [links.user_id]
    linksTo = ["tt_f_mbr_card.member_id",  "tt_f_user", "tt_f_user_role", "tt_f_member", "tt_f_coach", "tt_f_staff", "tt_f_subscribe", "tt_f_login", "tt_l_remark.operate_user_id", "tt_f_schedule.coach_id"]
    
    [links.member_id]
    linksTo = ["tt_f_member", "tt_f_mbr_card", "tt_f_subscribe_card"]
     
    [links.MBR_CARD_ID]
    linksTo = ["tt_f_mbr_card", "tt_l_mbrcard_chg", "tt_f_subscribe_pay.PAY_ID"]

    [links.CARD_ID]
    linksTo = ["tt_f_mbr_card", "tt_f_card", "tt_f_card_rule", "tt_f_card_timeslot"]
    
    [links.COURSE_ID]
    linksTo = ["tt_f_card_rule", "tt_f_schedule", "tt_f_course"]
    
    [links.COACH_ID]
    linksTo = ["tt_f_card_rule", "tt_f_coach", "tt_f_schedule", "tt_f_coach_rest"]
    
    [links.MOBILE]
    linksTo = ["tt_f_user", "tt_f_login"]
    
    [links.SCHEDULE_ID]
    linksTo = ["tt_f_schedule", "TT_F_SUBSCRIBE","tt_l_remark.ID_VALUE","tt_f_schedule_rule","TT_L_MBRCARD_CHG"]
    
    [links.role_id]
    linksTo = ["tt_f_role", "tt_f_user_role"]
    
    [links.operate_user_id]
    linksTo = ["tt_f_user.user_id", "tt_l_remark"]
    
    [links.COURSE_TYPE_ID]
    linksTo = ["tt_d_course_type.COURSE_TYPE_ID", "tt_f_schedule.COURSE_TYPE_ID"]
    
    [links.SUBSCRIBE_ID]
    linksTo = ["tt_f_subscribe", "tt_f_subscribe_pay"]
[entries]
    [entries.member]
    type = "input"
    placeholder = "手机号码/姓名/userId"
    label = "查找用户"
    sql = """\
    	select * from tt_f_user where nickname like '%{input}%' or mobile like '%{input}%' or user_id = '{input}';\
    	select ur.USER_ID, ur.role_id, r.role_name from TT_F_USER_ROLE ur left join tt_f_role r on ur.role_id = r.role_id where ur.USER_ID IN _result_0.USER_ID\
        """
    
    [entries.findMemberCard]
    type = "input"
    placeholder = "会员卡号"
    label = "查找会员卡"
    sql = "select * from tt_f_mbr_card where mbr_card_id = '{input}' or card_no = {input}"

    [entries.findMerchant]
    type = "link"
    label = "查找馆主"
    sql = "select * from tt_f_user where user_id in (select user_id from tt_f_user_role where role_id = '100')"
    
    [entries.findUserByCard]
    type = "input"
    placeholder = "会员卡号"
    label = "卡找会员"
    sql = "select * from tt_f_user where user_id in (select user_id from tt_f_member where member_id in (select member_id from tt_f_mbr_card where mbr_card_id = '{input}'))"
    
    [entries.memberWithCards]
    type = "link"
    label = "有卡会员"
    sql = "select * from tt_f_user where user_id in (select user_id from tt_f_member where member_id in (select member_id from tt_f_mbr_card where state != 0))"

    [entries.captcha]
    type = "input"
    placeholder = "输入手机号"
    label = "发60s验证码1234"
    action = "action=SetCaptcha,value={input}"