[links]
    [links.user_id]
    linksTo = ["tt_f_user", "tt_f_user_role", "tt_f_member", "tt_f_coach", "tt_f_staff", "tt_f_subscribe", "tt_f_login"]
    
    [links.member_id]
    linksTo = ["tt_f_member", "tt_f_mbr_card", "tt_f_subscribe_card"]
     
    [links.MBR_CARD_ID]
    linksTo = ["tt_f_mbr_card", "tt_l_mbrcard_chg"]

    [links.CARD_ID]
    linksTo = ["tt_f_mbr_card", "tt_f_card", "tt_f_card_rule"]
    
    [links.COURSE_ID]
    linksTo = ["tt_f_card_rule", "tt_f_schedule", "tt_f_course"]
    
    [links.COACH_ID]
    linksTo = ["tt_f_card_rule", "tt_f_coach", "tt_f_schedule", "tt_f_coach_rest"]
    
    [links.MOBILE]
    linksTo = ["tt_f_user", "tt_f_login"]
    
    [links.SCHEDULE_ID]
    linksTo = ["tt_f_schedule", "TT_F_SUBSCRIBE"]
    
    [links.role_id]
    linksTo = ["tt_f_role", "tt_f_user_role"]
    
[entries]
    [entries.member]
    type = "input"
    placeholder = "手机号码/姓名/userId"
    label = "查找用户"
    sql = """\
    	select * from tt_f_user where nickname like '%{input}%' or mobile like '%{input}%' or user_id = '{input}';\
    	select ur.USER_ID, ur.role_id, r.role_name from TT_F_USER_ROLE ur left join tt_f_role r on ur.role_id = r.role_id where ur.USER_ID IN _result_0.USER_ID\
        """


    [entries.findSubscribeInfoByCardName]
    type = "input"
    placeholder = "卡名称"
    label = "根据卡查找订课信息"
    sql ="""\
        select * from tt_f_card where CARD_NAME like '%{input}%';\
        select * from tt_f_mbr_card where CARD_ID in _result_last.CARD_ID;\
        select * from tt_f_subscribe_pay where PAY_ID in _result_last.MBR_CARD_ID;\
        select * from tt_f_subscribe where SUBSCRIBE_ID in _result_last.SUBSCRIBE_ID;\
        select * from TT_F_SCHEDULE where SCHEDULE_ID in _result_last.SCHEDULE_ID;\
        select * from TT_F_USER where USER_ID in _result_3.USER_ID;\
        """